### ISSUE TITLE
webserver fails to build

### ISSUE THREAD

**Issue by rcemper** [intersystems-ib/iris-fhir-interop#1]
Building webserver
Step 1/8 : FROM containers.intersystems.com/intersystems/webgateway**:2021.1.0.215.0**
ERROR: Service 'webserver' failed to build : manifest for containers.intersystems.com/intersystems/webgateway:2021.1.0.215.0 not found: mani fest unknown: The named manifest is not known to the registry.
*****  also no latest available '******
Building webserver
Step 1/8 : FROM containers.intersystems.com/intersystems/webgateway
ERROR: Service 'webserver' failed to build : manifest for containers.intersystems.com/intersystems/webgateway**:latest** not found: manifest unknown: The named manifest is not known to the registry.

**Comment by rcemper** [comment]
this image works: 
containers.intersystems.com/intersystems/webgateway:2022.1.0.209.0

**Comment by albertoft** [comment]
Fixed. Now using webgateway:2022.1.0.209.0.
